### ISSUE TITLE
Integrate brickss

### ISSUE THREAD

**Issue by Wolfr** [Wolfr/routify-site-2020#12]
I tried to integrate the current page from https://routify.now.sh/docs/install into this repo .

Some dependency errors. See https://github.com/Wolfr/routify-site-2020/tree/integratebrickss .

```
[!] Error: 'css' is not exported by node_modules/emotion/dist/emotion.umd.min.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/@sveltech/bricks/src/components/Modal.svelte (2:10)
1: <script>
2:   import {css} from "emotion/dist/emotion.umd.min.js";
             ^
3:   import { fade } from "svelte/transition";
4:   import { onDestroy } from "svelte";
Error: 'css' is not exported by node_modules/emotion/dist/emotion.umd.min.js
    at error (/Users/johanronsse/Sites/routify-site-2020/node_modules/rollup/dist/rollup.js:5365:30)
    at Module.error (/Users/johanronsse/Sites/routify-site-2020/node_modules/rollup/dist/rollup.js:9708:9)
    at handleMissingExport (/Users/johanronsse/Sites/routify-site-2020/node_modules/rollup/dist/rollup.js:9625:21)
    at Module.traceVariable (/Users/johanronsse/Sites/ro
```

**Comment by jakobrosenberg** [comment]
That's an odd one. I thought another dependency had snuck into devDependencies, but everything seems to be alright.

Can you see what files are in "node_modules/emotion/dist/"?

**Comment by Wolfr** [comment]
There files:

```
emotion.cjs.dev.js
emotion.cjs.js
emotion.cjs.js.flow
emotion.cjs.prod.js
emotion.esm.js
emotion.umd.min.js
emotion.umd.min.js.map
```
